databases:
  - name: mort
    ipAllowList: []
    region: frankfurt
    plan: free

services:
  - type: web
    plan: free
    name: mort
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 main.py
    region: frankfurt
    envVars:
      - key: API_HASH 
        sync: false
      - key: API_ID 
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mort 
          property: connectionString
    autoDeploy: false
